#pragma once

enum ENextFrame {
    START = 0,
    FIRST_HELLO = 1,
    FIRST_HELLO_USER_ACTION = 2,
    FIRST_TOUCH = 3,
    FIRST_TOUCH_USER_ACTION = 4,
    WILL_YOU_HELP = 5,
    WILL_YOU_HELP_USER_ACTION = 6,
    AGREED_TO_HELP = 7,
    AGREED_TO_HELP_USER_ACTION = 8,
    LABYRINTH = 9,
    LABYRINTH_USER_ACTION = 10,
    ESCAPED = 11,
    FACE = 12,
    ENDING = 13
};
